name: Test Before Merging to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        platform: [ubuntu-latest]
        target: [x86_64-unknown-linux-gnu]
        include:
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install libsystemd-dev
        run: sudo apt-get install libsystemd-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.87.0
        with:
          components: rustfmt, clippy
          targets: ${{ matrix.target }}
      
      - name: Run Tests
        run: cargo test --verbose
